// <auto-generated />
using System;
using GerenciadorPresenca.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciadorPresenca.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260505214315_AdicionaConvidadoPrincipalId")]
    partial class AdicionaConvidadoPrincipalId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GerenciadorPresenca.Model.Convidado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ConvidadoPrincipalId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeCrianca")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Convidados");
                });
#pragma warning restore 612, 618
        }
    }
}
